name: GoogleTest CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ cmake libgtest-dev make

      # 3. Build GoogleTest
      - name: Build GoogleTest
        run: |
          cd /usr/src/googletest
          sudo cmake .
          sudo make
          # статические библиотеки будут в /usr/src/googletest/lib/
          ls -l lib

      # 4. Compile project with GoogleTest
      - name: Build project
        run: |
          g++ -std=c++17 \
            student_lib.cpp tests.cpp \
            /usr/src/googletest/lib/libgtest.a \
            /usr/src/googletest/lib/libgtest_main.a \
            -pthread -o test_program

      # 5. Run tests
      - name: Run tests
        run: ./test_program
